# Generated by Django 5.2 on 2026-01-06 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('client_reference', models.CharField(blank=True, max_length=50)),
                ('titre', models.CharField(max_length=255)),
                ('texte', models.TextField(blank=True)),
                ('code_type', models.CharField(blank=True, max_length=10)),
                ('contact_nom', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_telephone', models.CharField(blank=True, max_length=20)),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('nb_pieces', models.PositiveIntegerField(blank=True, null=True)),
                ('nb_chambres', models.PositiveIntegerField(blank=True, null=True)),
                ('surface', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('annee_construction', models.PositiveIntegerField(blank=True, null=True)),
                ('dpe_etiquette_conso', models.CharField(blank=True, max_length=1)),
                ('dpe_valeur_conso', models.PositiveIntegerField(blank=True, null=True)),
                ('dpe_etiquette_ges', models.CharField(blank=True, max_length=1)),
                ('type_transaction', models.CharField(choices=[('V', 'Vente'), ('L', 'Location')], default='V', max_length=1)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('honoraires_payeurs', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.annonce')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['ordre'],
            },
        ),
    ]
