# Generated by Django 5.2 on 2026-03-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_favori'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='charges_locatives',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='depot_garantie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='dpe_date_realisation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='annonce',
            name='dpe_valeur_ges',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='frais_agence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='honoraires_location',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='libelle_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='annonce',
            name='loyer_mensuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='montant_depenses_energies_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='montant_depenses_energies_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='surface_sejour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='surface_terrain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='code_postal',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='type_transaction',
            field=models.CharField(choices=[('V', 'Vente'), ('L', 'Location'), ('S', 'Saisonnier'), ('F', 'Fonds de commerce'), ('B', 'Bail commercial'), ('W', 'Viager'), ('G', 'Neuf (VEFA)')], default='V', max_length=1),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='ville',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
