# Generated by Django 5.2 on 2026-03-20 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_add_xml_feed_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('metier', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True, max_length=500)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'ordering': ['metier', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('feed_url', models.URLField(blank=True, max_length=500)),
                ('feed_type', models.CharField(choices=[('url', 'URL publique'), ('ftp', 'FTP')], default='url', max_length=10)),
                ('contact_nom', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_import', models.DateTimeField(blank=True, null=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agence',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decorations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspiration deco',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecoCommentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deco_commentaires', to=settings.AUTH_USER_MODEL)),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='listings.decoration')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
