# Generated by Django 5.2 on 2026-03-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_partenaire_agence_decoration_decocommentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='is_inspiration',
            field=models.BooleanField(default=False),
        ),
    ]
