# Generated by Django 5.2 on 2026-03-22 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_add_inspiration_categorie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=200)),
                ('metier', models.CharField(choices=[('decorateur', "Decorateur d'interieur"), ('architecte', "Architecte d'interieur"), ('peintre', 'Peintre'), ('plombier', 'Plombier'), ('electricien', 'Electricien'), ('jardinier', 'Paysagiste'), ('cuisiniste', 'Cuisiniste'), ('menuisier', 'Menuisier'), ('carreleur', 'Carreleur'), ('macon', 'Macon'), ('couvreur', 'Couvreur'), ('serrurier', 'Serrurier'), ('domotique', 'Domotique'), ('renovation', 'Renovation generale'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('site_web', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Pro',
                'verbose_name_plural': 'Profils Pro',
            },
        ),
        migrations.CreateModel(
            name='DemandeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('annonce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_contact', to='listings.annonce')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_envoyees', to=settings.AUTH_USER_MODEL)),
                ('pro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_contact', to='listings.proprofile')),
            ],
            options={
                'verbose_name': 'Demande de contact',
                'verbose_name_plural': 'Demandes de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProRealisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(blank=True, choices=[('chaleureux', 'Foyer chaleureux'), ('architecte', 'Deco architecte'), ('moderne', 'Design moderne'), ('nature', 'Esprit nature'), ('luxe', 'Standing & luxe'), ('cosy', 'Ambiance cosy'), ('scandinave', 'Style scandinave'), ('industriel', 'Loft industriel'), ('famille', 'Maison de famille'), ('jardin', 'Terrasse & jardin')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisations', to='listings.proprofile')),
            ],
            options={
                'verbose_name': 'Realisation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProRealisationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('realisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.prorealisation')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='PhotoNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='listings.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_notes', to=settings.AUTH_USER_MODEL)),
                ('photo_pro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='listings.prorealisationphoto')),
            ],
            options={
                'verbose_name': 'Note Photo',
                'verbose_name_plural': 'Notes Photos',
            },
        ),
        migrations.CreateModel(
            name='PhotoFavori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_favoris', to='listings.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_favoris', to=settings.AUTH_USER_MODEL)),
                ('photo_pro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_favoris', to='listings.prorealisationphoto')),
            ],
            options={
                'verbose_name': 'Favori Photo',
                'verbose_name_plural': 'Favoris Photos',
            },
        ),
        migrations.CreateModel(
            name='ProAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveIntegerField()),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_donnes', to=settings.AUTH_USER_MODEL)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='listings.proprofile')),
            ],
            options={
                'verbose_name': 'Avis Pro',
                'verbose_name_plural': 'Avis Pro',
                'ordering': ['-created_at'],
                'unique_together': {('pro', 'auteur')},
            },
        ),
    ]
