# Generated by Django 5.2 on 2026-03-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_social_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='inspiration_categorie',
            field=models.CharField(blank=True, choices=[('chaleureux', 'Foyer chaleureux'), ('architecte', 'Deco architecte'), ('moderne', 'Design moderne'), ('nature', 'Esprit nature'), ('luxe', 'Standing & luxe'), ('cosy', 'Ambiance cosy'), ('scandinave', 'Style scandinave'), ('industriel', 'Loft industriel'), ('famille', 'Maison de famille'), ('jardin', 'Terrasse & jardin')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_inspiration',
            field=models.BooleanField(default=False),
        ),
    ]
