# Generated by Django 5.2 on 2026-03-22 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_photocommentaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conseiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conseillers', to='listings.agence')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conseiller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conseiller',
                'verbose_name_plural': 'Conseillers',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='annonce',
            name='conseiller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces', to='listings.conseiller'),
        ),
    ]
