# Generated by Django 5.2 on 2026-03-23 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_conseiller_annonce_conseiller'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='code_postal',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='agence',
            name='departement',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='agence',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agence',
            name='siret',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='SIRET/RCS'),
        ),
        migrations.AddField(
            model_name='agence',
            name='ville',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='code_postal',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='departement',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='siret',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='SIRET/RCS'),
        ),
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_bien', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('terrain', 'Terrain'), ('commerce', 'Local commercial'), ('bureau', 'Bureau'), ('autre', 'Autre')], max_length=50)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('surface', models.PositiveIntegerField(blank=True, null=True)),
                ('nb_pieces', models.PositiveIntegerField(blank=True, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_treated', models.BooleanField(default=False)),
                ('agence_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations', to='listings.agence')),
            ],
            options={
                'verbose_name': "Demande d'estimation",
                'ordering': ['-created_at'],
            },
        ),
    ]
