# Generated by Django 5.2 on 2026-03-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_annuaire_estimation'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='horaires',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="Horaires d'ouverture"),
        ),
        migrations.AddField(
            model_name='agence',
            name='site_web',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
