# Generated by Django 5.2 on 2026-03-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_agence_settings_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
