# Generated by Django 5.2 on 2026-03-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_agence_logo_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='mise_en_avant',
            field=models.BooleanField(default=False, verbose_name='Mise à la une'),
        ),
    ]
