# Generated by Django 5.2 on 2026-03-23 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_mise_en_avant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenceOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mise_en_avant', models.BooleanField(default=False, help_text='Permet de mettre des annonces a la une (priorite dans les recherches)', verbose_name='Mise a la une')),
                ('nb_mises_en_avant', models.PositiveIntegerField(default=0, verbose_name='Nb annonces a la une autorisees')),
                ('remontee_auto', models.BooleanField(default=False, help_text='Remonter les annonces en tete toutes les 48h', verbose_name='Remontee automatique')),
                ('badge_premium', models.BooleanField(default=False, help_text='Badge dore "Premium" sur toutes les annonces de l\'agence', verbose_name='Badge Premium')),
                ('logo_sur_annonces', models.BooleanField(default=False, help_text="Afficher le logo de l'agence sur chaque annonce", verbose_name='Logo sur annonces')),
                ('page_vitrine', models.BooleanField(default=False, help_text='Page agence enrichie avec description, photos, avis', verbose_name='Page vitrine personnalisee')),
                ('bandeau_exclusif', models.BooleanField(default=False, help_text='Afficher "Exclusivite" sur certaines annonces', verbose_name='Bandeau Exclusif')),
                ('estimation_forward', models.BooleanField(default=False, help_text="Recevoir les demandes d'estimation de sa zone", verbose_name='Reception estimations')),
                ('contact_prioritaire', models.BooleanField(default=False, help_text='Formulaire de contact enrichi avec rappel telephonique', verbose_name='Contact prioritaire')),
                ('alertes_email', models.BooleanField(default=False, help_text='Envoyer les nouvelles annonces aux acheteurs inscrits dans la zone', verbose_name='Alertes email acheteurs')),
                ('stats_avancees', models.BooleanField(default=False, help_text='Nombre de vues, clics, favoris par annonce + tendances', verbose_name='Statistiques avancees')),
                ('rapport_mensuel', models.BooleanField(default=False, help_text='Email recapitulatif mensuel avec performances', verbose_name='Rapport mensuel')),
                ('donnees_marche', models.BooleanField(default=False, help_text='Prix au m2, tendances du secteur, comparatifs', verbose_name='Donnees de marche')),
                ('visite_virtuelle', models.BooleanField(default=False, help_text='Integration de visites 3D (Matterport, etc.)', verbose_name='Visite virtuelle')),
                ('video', models.BooleanField(default=False, help_text='Integrer des videos YouTube/Vimeo sur les annonces', verbose_name='Videos')),
                ('photos_illimitees', models.BooleanField(default=False, help_text='Pas de limite sur le nombre de photos par annonce', verbose_name='Photos illimitees')),
                ('multidiffusion', models.BooleanField(default=False, help_text="Diffuser sur SeLoger, LeBonCoin, Bien'ici, etc.", verbose_name='Multidiffusion')),
                ('export_portails', models.BooleanField(default=False, help_text='Generer un flux XML compatible portails immobiliers', verbose_name='Export portails')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes_admin', models.TextField(blank=True, default='', help_text="Notes visibles uniquement par l'admin", verbose_name='Notes internes')),
                ('agence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='listings.agence')),
            ],
            options={
                'verbose_name': 'Options agence',
                'verbose_name_plural': 'Options agences',
            },
        ),
    ]
