# Generated by Django 5.2 on 2026-03-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_agence_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='mise_en_avant',
            field=models.BooleanField(default=False, verbose_name='A la une sur la homepage'),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='mise_en_avant',
            field=models.BooleanField(default=False, verbose_name='A la une sur la homepage'),
        ),
    ]
