# Generated by Django 5.2 on 2026-03-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_agence_pro_mise_en_avant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenceoptions',
            name='export_portails',
        ),
        migrations.RemoveField(
            model_name='agenceoptions',
            name='multidiffusion',
        ),
        migrations.AddField(
            model_name='annonce',
            name='nb_vues',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de vues'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL Video (YouTube/Vimeo)'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='visite_virtuelle_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL Visite virtuelle (Matterport/360)'),
        ),
    ]
