# Generated by Django 5.2 on 2026-03-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_annonce_video_visite_vues_remove_diffusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecontact',
            name='creneau_rappel',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Creneau de rappel'),
        ),
    ]
