# Generated by Django 5.2 on 2026-03-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_contact_creneau_rappel'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='feed_format',
            field=models.CharField(choices=[('ac3', 'XML (AC3/Ubiflow)'), ('poliris', 'CSV (Poliris)')], default='ac3', max_length=10, verbose_name='Format du flux'),
        ),
        migrations.AddField(
            model_name='agence',
            name='ftp_host',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Serveur FTP'),
        ),
        migrations.AddField(
            model_name='agence',
            name='ftp_password',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Mot de passe FTP'),
        ),
        migrations.AddField(
            model_name='agence',
            name='ftp_path',
            field=models.CharField(blank=True, default='/', max_length=500, verbose_name='Chemin FTP'),
        ),
        migrations.AddField(
            model_name='agence',
            name='ftp_user',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Utilisateur FTP'),
        ),
    ]
