# Generated by Django 5.2 on 2026-03-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_agence_feed_format_ftp'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspirationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('groupe', models.CharField(choices=[('style', 'Style'), ('piece', 'Piece'), ('couleur', 'Couleur'), ('materiau', 'Materiau'), ('ambiance', 'Ambiance')], default='style', max_length=20)),
                ('icone', models.CharField(blank=True, default='', max_length=10)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tag inspiration',
                'verbose_name_plural': 'Tags inspiration',
                'ordering': ['groupe', 'ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='photos', to='listings.inspirationtag'),
        ),
        migrations.AddField(
            model_name='prorealisation',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='realisations', to='listings.inspirationtag'),
        ),
    ]
