# Generated by Django 5.2 on 2026-03-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_inspiration_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprofile',
            name='metier',
            field=models.CharField(choices=[('decorateur', "Decorateur d'interieur"), ('architecte', "Architecte d'interieur"), ('home_stager', 'Home stager'), ('cuisiniste', 'Cuisiniste'), ('macon', 'Macon'), ('charpentier', 'Charpentier'), ('couvreur', 'Couvreur'), ('facadier', 'Facadier / Ravalement'), ('peintre', 'Peintre'), ('plombier', 'Plombier'), ('electricien', 'Electricien'), ('carreleur', 'Carreleur'), ('menuisier', 'Menuisier'), ('plaquiste', 'Plaquiste / Platrier'), ('serrurier', 'Serrurier'), ('vitrier', 'Vitrier'), ('storiste', 'Storiste / Fermetures'), ('chauffagiste', 'Chauffagiste / Climatisation'), ('isolation', 'Isolation / RGE'), ('domotique', 'Domotique'), ('paysagiste', 'Paysagiste / Jardinier'), ('pisciniste', 'Pisciniste'), ('photographe', 'Photographe immobilier'), ('diagnostiqueur', 'Diagnostiqueur immobilier'), ('geometre', 'Geometre-expert'), ('courtier_travaux', 'Courtier en travaux'), ('demenageur', 'Demenageur'), ('nettoyage', 'Nettoyage / Conciergerie'), ('renovation', 'Renovation generale'), ('autre', 'Autre')], max_length=50),
        ),
    ]
