# Generated by Django 5.2 on 2026-03-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_extend_metier_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='prorealisationphoto',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='realisations/'),
        ),
        migrations.AlterField(
            model_name='prorealisationphoto',
            name='url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
