# Generated by Django 5.2 on 2026-04-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_pro_photo_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenceoptions',
            name='inspiration_a_la_une',
            field=models.BooleanField(default=False, help_text='Permet de mettre des photos inspiration a la une sur la homepage', verbose_name='Inspirations a la une'),
        ),
        migrations.AddField(
            model_name='agenceoptions',
            name='nb_inspirations_une',
            field=models.PositiveIntegerField(default=0, help_text='Quota de photos inspiration pouvant etre mises a la une', verbose_name='Nb inspirations a la une autorisees'),
        ),
        migrations.AddField(
            model_name='photo',
            name='mise_en_avant',
            field=models.BooleanField(default=False, verbose_name='A la une inspirations'),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='inspiration_a_la_une',
            field=models.BooleanField(default=False, verbose_name='Inspirations a la une'),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='nb_inspirations_une',
            field=models.PositiveIntegerField(default=0, verbose_name='Nb inspirations a la une autorisees'),
        ),
        migrations.AddField(
            model_name='prorealisationphoto',
            name='mise_en_avant',
            field=models.BooleanField(default=False, verbose_name='A la une inspirations'),
        ),
    ]
