# Generated by Django 5.2 on 2026-07-02 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_annonce_source_annonce_user_photo_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RechercheSauvegardee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(blank=True, default='', max_length=100)),
                ('type_transaction', models.CharField(blank=True, default='', max_length=2)),
                ('prix_min', models.PositiveIntegerField(blank=True, null=True)),
                ('prix_max', models.PositiveIntegerField(blank=True, null=True)),
                ('surface_min', models.PositiveIntegerField(blank=True, null=True)),
                ('pieces_min', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('derniere_alerte', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recherches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recherche sauvegardee',
                'verbose_name_plural': 'Recherches sauvegardees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VilleGeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(blank=True, default='', max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ville geocodee',
                'verbose_name_plural': 'Villes geocodees',
                'unique_together': {('ville', 'code_postal')},
            },
        ),
    ]
