# Generated by Django 5.2 on 2026-07-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_recherchesauvegardee_villegeo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_thumb',
            field=models.ImageField(blank=True, default='', upload_to='annonces/thumbs/'),
        ),
        migrations.AddField(
            model_name='prorealisationphoto',
            name='image_thumb',
            field=models.ImageField(blank=True, default='', upload_to='realisations/thumbs/'),
        ),
    ]
