# Generated by Django 5.2 on 2026-07-02 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_photo_image_thumb_prorealisationphoto_image_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces', to='listings.agence'),
        ),
    ]
