# Generated by Django 5.2 on 2026-07-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_remplir_annonce_agence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decocommentaire',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='decocommentaire',
            name='decoration',
        ),
        migrations.RemoveField(
            model_name='decoration',
            name='auteur',
        ),
        migrations.DeleteModel(
            name='Partenaire',
        ),
        migrations.DeleteModel(
            name='DecoCommentaire',
        ),
        migrations.DeleteModel(
            name='Decoration',
        ),
    ]
