# Generated by Django 5.2 on 2026-07-02 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_remove_decocommentaire_auteur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommuneDVF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_insee', models.CharField(max_length=5, unique=True)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(blank=True, default='', max_length=10)),
                ('derniere_maj', models.DateTimeField(blank=True, null=True)),
                ('nb_ventes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Commune DVF',
                'verbose_name_plural': 'Communes DVF',
            },
        ),
        migrations.CreateModel(
            name='VenteDVF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_local', models.CharField(choices=[('maison', 'Maison'), ('appartement', 'Appartement')], max_length=15)),
                ('surface', models.PositiveIntegerField()),
                ('prix', models.PositiveIntegerField()),
                ('date_mutation', models.DateField()),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='listings.communedvf')),
            ],
            options={
                'verbose_name': 'Vente DVF',
                'verbose_name_plural': 'Ventes DVF',
                'ordering': ['-date_mutation'],
                'indexes': [models.Index(fields=['commune', 'type_local'], name='listings_ve_commune_e44fd3_idx')],
            },
        ),
    ]
