# Generated by Django 5.2 on 2026-07-02 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_communedvf_ventedvf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abonnement', models.CharField(choices=[('agence', 'Abonnement Agence Premium'), ('pro', 'Abonnement Artisan Pro'), ('pack_vendeur', 'Pack Vendeur Pro (30 jours)')], max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('impaye', 'Impaye'), ('resilie', 'Resilie')], default='actif', max_length=10)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=100)),
                ('date_fin', models.DateTimeField(blank=True, help_text='Fin du boost (pack vendeur)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annonce', models.ForeignKey(blank=True, help_text='Annonce boostee (pack vendeur)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boosts', to='listings.annonce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(choices=[('compte', 'Mon compte'), ('annonce', 'Mon annonce'), ('paiement', 'Paiement / facturation'), ('technique', 'Probleme technique'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('message', models.TextField()),
                ('is_traite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket support',
                'verbose_name_plural': 'Tickets support',
                'ordering': ['-created_at'],
            },
        ),
    ]
