# Generated by Django 5.2 on 2026-07-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0032_abonnement_ticketsupport'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('visites', models.PositiveIntegerField(default=0)),
                ('estimations', models.PositiveIntegerField(default=0)),
                ('depots_annonces', models.PositiveIntegerField(default=0)),
                ('alertes_creees', models.PositiveIntegerField(default=0)),
                ('demandes_devis', models.PositiveIntegerField(default=0)),
                ('inscriptions', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistiques du jour',
                'verbose_name_plural': 'Statistiques quotidiennes',
                'ordering': ['-date'],
            },
        ),
    ]
