# Generated by Django 5.2 on 2026-07-04 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_statjour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='checkout_session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['is_active', 'type_transaction'], name='listings_an_is_acti_e5d507_idx'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['is_active', 'mise_en_avant'], name='listings_an_is_acti_3de132_idx'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['is_active', 'ville'], name='listings_an_is_acti_5ad55a_idx'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['prix'], name='listings_an_prix_7bc804_idx'),
        ),
    ]
