# Generated by Django 5.2 on 2026-07-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_abonnement_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprofile',
            name='google_business_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Lien Google (fiche/avis)'),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='nom_officiel',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Raison sociale officielle'),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='siret_verifie',
            field=models.BooleanField(default=False, verbose_name='SIRET verifie (entreprise reelle et active)'),
        ),
    ]
