# Generated by Django 5.2 on 2026-07-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_proprofile_google_business_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='checkout_session_id',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, unique=True),
        ),
    ]
