# Generated by Django 5.2 on 2026-07-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0037_demandecontact_email_demandecontact_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favori',
            name='prix_reference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
