# Generated by Django 5.2 on 2026-07-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0038_favori_prix_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agence', models.CharField(max_length=200, verbose_name="Nom de l'agence")),
                ('ville', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('nb_biens', models.CharField(blank=True, default='', max_length=50, verbose_name='Nombre de biens')),
                ('message', models.TextField(blank=True, default='')),
                ('email_envoye', models.BooleanField(default=False, verbose_name='Email admin envoye')),
                ('is_traitee', models.BooleanField(default=False, verbose_name='Traitee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Demande d'agence",
                'verbose_name_plural': "Demandes d'agences",
                'ordering': ['-created_at'],
            },
        ),
    ]
