# Generated by Django 5.2 on 2026-07-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0039_demandeagence'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprofile',
            name='autres_metiers',
            field=models.CharField(blank=True, default='', help_text="Specialites supplementaires, separees par des virgules (entreprises tous corps d'etat).", max_length=200, verbose_name='Autres corps de metier'),
        ),
        migrations.AlterField(
            model_name='proprofile',
            name='metier',
            field=models.CharField(choices=[('decorateur', "Decorateur d'interieur"), ('architecte', "Architecte d'interieur"), ('home_stager', 'Home stager'), ('cuisiniste', 'Cuisiniste'), ('macon', 'Macon'), ('charpentier', 'Charpentier'), ('couvreur', 'Couvreur'), ('facadier', 'Facadier / Ravalement'), ('peintre', 'Peintre'), ('plombier', 'Plombier'), ('electricien', 'Electricien'), ('carreleur', 'Carreleur'), ('menuisier', 'Menuisier'), ('plaquiste', 'Plaquiste / Platrier'), ('serrurier', 'Serrurier'), ('vitrier', 'Vitrier'), ('storiste', 'Storiste / Fermetures'), ('chauffagiste', 'Chauffagiste / Climatisation'), ('isolation', 'Isolation / RGE'), ('domotique', 'Domotique'), ('paysagiste', 'Paysagiste / Jardinier'), ('pisciniste', 'Pisciniste'), ('photographe', 'Photographe immobilier'), ('diagnostiqueur', 'Diagnostiqueur immobilier'), ('geometre', 'Geometre-expert'), ('courtier_travaux', 'Courtier en travaux'), ('demenageur', 'Demenageur'), ('nettoyage', 'Nettoyage / Conciergerie'), ('tous_corps_etat', "Tous corps d'etat"), ('renovation', 'Renovation generale'), ('autre', 'Autre')], max_length=50),
        ),
    ]
