# Generated by Django 5.2 on 2026-07-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_proprofile_autres_metiers_alter_proprofile_metier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
                ('section', models.CharField(blank=True, default='', max_length=20)),
                ('referer_host', models.CharField(blank=True, default='', max_length=200)),
                ('visiteur_hash', models.CharField(max_length=64)),
                ('is_mobile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Page vue',
                'verbose_name_plural': 'Pages vues',
                'indexes': [models.Index(fields=['created_at'], name='listings_pa_created_7829d7_idx'), models.Index(fields=['visiteur_hash', 'created_at'], name='listings_pa_visiteu_522288_idx'), models.Index(fields=['section', 'created_at'], name='listings_pa_section_fd019f_idx')],
            },
        ),
    ]
