# Generated by Django 5.2 on 2026-07-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0041_pagevue'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='relance_envoyee',
            field=models.BooleanField(default=False, verbose_name='Relance email envoyee'),
        ),
    ]
