# Generated by Django 5.2 on 2026-07-10 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0042_estimation_relance_envoyee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='proprofile',
            index=models.Index(fields=['is_active', 'departement', 'metier'], name='listings_pr_is_acti_33d609_idx'),
        ),
        migrations.AddIndex(
            model_name='proprofile',
            index=models.Index(fields=['is_active', 'mise_en_avant'], name='listings_pr_is_acti_d0376e_idx'),
        ),
        migrations.AddIndex(
            model_name='villegeo',
            index=models.Index(fields=['latitude', 'longitude'], name='listings_vi_latitud_272ceb_idx'),
        ),
    ]
