# Generated by Django 5.2 on 2026-07-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0043_proprofile_listings_pr_is_acti_33d609_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desabonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Desabonnement email',
                'verbose_name_plural': 'Desabonnements email',
            },
        ),
    ]
