# Generated by Django 5.2 on 2026-07-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0044_desabonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='proavis',
            name='verifie',
            field=models.BooleanField(default=False, help_text="True si l'auteur a reellement contacte ce pro (preuve d'interaction).", verbose_name='Avis verifie'),
        ),
    ]
