# Generated by Django 5.2 on 2026-07-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0045_proavis_verifie'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='ascenseur',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ascenseur'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='etage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Etage'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='exterieur',
            field=models.CharField(blank=True, choices=[('', '—'), ('balcon', 'Balcon'), ('terrasse', 'Terrasse'), ('jardin', 'Jardin'), ('loggia', 'Loggia')], default='', max_length=20, verbose_name='Exterieur'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='meuble',
            field=models.BooleanField(blank=True, null=True, verbose_name='Meuble'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='parking',
            field=models.BooleanField(blank=True, null=True, verbose_name='Parking / garage'),
        ),
    ]
