# Generated by Django 5.2 on 2026-07-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0048_rendezvous'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='photos_illimitees',
            field=models.BooleanField(default=False, verbose_name='Photos illimitees (option payante)'),
        ),
    ]
