# Generated by Django 5.2 on 2026-07-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0049_annonce_photos_illimitees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='type_abonnement',
            field=models.CharField(choices=[('agence', 'Abonnement Agence Premium'), ('agence_illimite', 'Abonnement Agence Illimite'), ('pro', 'Abonnement Artisan Pro'), ('pro_priorite_secteur', 'Priorite Secteur (pro)'), ('pack_vendeur', 'Pack Vendeur Pro (30 jours)'), ('vendeur_photos', 'Photos illimitees'), ('vendeur_alaune_7', 'A la une 7 jours'), ('vendeur_alaune_30', 'A la une 30 jours')], max_length=20),
        ),
    ]
