# Generated by Django 5.2 on 2026-07-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0050_alter_abonnement_type_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='equip_animaux',
            field=models.BooleanField(default=False, verbose_name='Animaux acceptés'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='equip_clim',
            field=models.BooleanField(default=False, verbose_name='Climatisation'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='equip_cuisine',
            field=models.BooleanField(default=False, verbose_name='Cuisine équipée'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='equip_lave_linge',
            field=models.BooleanField(default=False, verbose_name='Lave-linge'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='equip_piscine',
            field=models.BooleanField(default=False, verbose_name='Piscine'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='equip_tv',
            field=models.BooleanField(default=False, verbose_name='Télévision'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='equip_wifi',
            field=models.BooleanField(default=False, verbose_name='Wifi'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='frais_menage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Frais de ménage'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='nb_lits',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nombre de lits'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='nb_voyageurs',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Voyageurs (capacité)'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='nuits_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nuits minimum'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='prix_nuit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix par nuit'),
        ),
    ]
