"""
Django settings for social_immo project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charger les variables d'environnement depuis .env
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Defaut = False (securise) : si le .env n'est pas charge en prod, on ne
# tombe jamais en DEBUG. Le developpement local active DEBUG=True dans son .env.
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# SECURITY WARNING: keep the secret key used in production secret!
# En production (DEBUG=False), SECRET_KEY DOIT venir de l'environnement.
SECRET_KEY = os.environ.get('SECRET_KEY', '')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-cle-de-dev-uniquement'
    else:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            'SECRET_KEY manquante : definissez-la dans le fichier .env '
            '(generez-en une avec : python -c "from django.core.management.utils '
            'import get_random_secret_key; print(get_random_secret_key())")'
        )

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0,192.168.1.135').split(',')

# CSRF trusted origins for Railway/production
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost,http://127.0.0.1').split(',')

# SSL / HTTPS en production (o2switch : SSL termine par Apache, on est derriere un proxy)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Force la redirection HTTP -> HTTPS
    SECURE_SSL_REDIRECT = True
    # HSTS : demarrage prudent a 1h. Passer a 31536000 (1 an) + preload une
    # fois confirme que TOUT le site (sous-domaines inclus) est en HTTPS.
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Durcissements explicites (defauts surs, poses noir sur blanc)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'listings',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise pour fichiers statiques
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'listings.middleware.StatsMiddleware',
]

ROOT_URLCONF = 'social_immo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'listings.context_processors.user_roles',
            ],
        },
    },
]

WSGI_APPLICATION = 'social_immo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuration automatique : utilise DATABASE_URL si disponible, sinon SQLite
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Production : PostgreSQL ou MySQL via DATABASE_URL
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif os.environ.get('MYSQL_HOST'):
    # Production MySQL (o2switch)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('MYSQL_DATABASE', 'socialimmo'),
            'USER': os.environ.get('MYSQL_USER', ''),
            'PASSWORD': os.environ.get('MYSQL_PASSWORD', ''),
            'HOST': os.environ.get('MYSQL_HOST', ''),
            'PORT': os.environ.get('MYSQL_PORT', '3306'),
            # Connexions persistantes : evite un handshake MySQL a chaque requete.
            # 60s (court) car o2switch coupe vite les connexions idle ; le health
            # check evite les "MySQL server has gone away".
            'CONN_MAX_AGE': 60,
            'CONN_HEALTH_CHECKS': True,
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
else:
    # Développement local : SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Tests : toujours une base SQLite en memoire, quel que soit l'environnement.
# Rapide, et surtout evite l'erreur "Access denied ... CREATE DATABASE" sur
# l'hebergement mutualise o2switch (l'utilisateur MySQL ne peut pas creer la
# base de test). N'affecte QUE `manage.py test`, jamais la prod.
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Dossier où collectstatic met les fichiers

# WhiteNoise configuration pour servir les fichiers statiques en production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# django-allauth
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'EMAIL_AUTHENTICATION': True,
    },
}

# Email configuration
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@social-immo.com')

# Logging - erreurs dans un fichier (avec rotation) + email a l'admin sur les 500
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            # RotatingFileHandler : evite que django_errors.log sature le quota
            # disque o2switch (5 fichiers de 2 Mo max).
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'django_errors.log',
            'maxBytes': 2 * 1024 * 1024,
            'backupCount': 5,
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
        },
    },
    'loggers': {
        # Les exceptions 500 passent par 'django.request' : on les envoie par
        # email aux ADMINS (en plus du fichier). propagate=False pour ne pas
        # doublonner via le logger 'django' parent.
        'django.request': {
            'handlers': ['file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

# Social Immo - Configuration du flux XML
SOCIALIMMO_AGENCE_ID = os.environ.get('SOCIALIMMO_AGENCE_ID', '')
SOCIALIMMO_FEED_URL = os.environ.get(
    'SOCIALIMMO_FEED_URL',
    'https://logiciel-immo-clean.vercel.app/api/export/socialimmo/'
)


# ===== Stripe (dormant tant que les cles ne sont pas definies) =====
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
STRIPE_PRICE_AGENCE = os.environ.get('STRIPE_PRICE_AGENCE', '')
STRIPE_PRICE_PRO = os.environ.get('STRIPE_PRICE_PRO', '')
STRIPE_PRICE_PACK = os.environ.get('STRIPE_PRICE_PACK', '')
# Phase 2 : options a la carte
STRIPE_PRICE_AGENCE_ILLIMITE = os.environ.get('STRIPE_PRICE_AGENCE_ILLIMITE', '')
STRIPE_PRICE_PRO_PRIORITE = os.environ.get('STRIPE_PRICE_PRO_PRIORITE', '')
STRIPE_PRICE_VENDEUR_PHOTOS = os.environ.get('STRIPE_PRICE_VENDEUR_PHOTOS', '')
STRIPE_PRICE_VENDEUR_ALAUNE_7 = os.environ.get('STRIPE_PRICE_VENDEUR_ALAUNE_7', '')
STRIPE_PRICE_VENDEUR_ALAUNE_30 = os.environ.get('STRIPE_PRICE_VENDEUR_ALAUNE_30', '')

# ===== Alertes erreurs : les exceptions 500 partent par email =====
_admin_email = os.environ.get('ADMIN_EMAIL', '')
ADMINS = [('Admin', _admin_email)] if _admin_email else []
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', DEFAULT_FROM_EMAIL)


# ===== Cache partage entre workers (rate-limiting, verrous DVF, blocs caches) =====
# DatabaseCache : sans dependance, compatible o2switch, partage entre process
# (contrairement a LocMemCache qui est par-worker). Table creee par
# `python manage.py createcachetable` (inclus dans autopilot au 1er run).
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'socialimmo_cache',
        'TIMEOUT': 300,
    }
}


# ===== Securite uploads : limite de taille (anti-DoS) =====
# 10 Mo par fichier ; au-dela, rejet avant traitement.
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = 2000
